spring:
  application:
    name: ElasticSearchExampleSerivce
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true

server:
  port: 8081

---
spring:
  profiles: dev
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true

server:
  port: 8081

---
spring:
  profiles: int

---
spring:
  profiles: uat

---
spring:
  profiles: prod