spring:
  application:
    name: ElasticSearchExampleSerivce
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    platform: H2
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true

server:
  port: 8081

---
spring:
  profiles: dev
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: docker-cluster
      repositories:
        enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  port: 8081

---
spring:
  profiles: int

---
spring:
  profiles: uat

---
spring:
  profiles: prod